#!/usr/bin/env python3
"""Amazon Crawler Report Generator.

Generate comprehensive analysis reports from Amazon crawler CSV output.
"""
import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

import pandas as pd


class CrawlerReport:
    """Generate reports from Amazon crawler CSV data."""

    def __init__(self, csv_path: str):
        """Initialize report generator.

        Args:
            csv_path: Path to the CSV file generated by crawler
        """
        self.csv_path = Path(csv_path)
        if not self.csv_path.exists():
            raise FileNotFoundError(f"CSV file not found: {csv_path}")

        self.df = pd.read_csv(self.csv_path)
        self._prepare_data()

    def _prepare_data(self):
        """Prepare and clean data for analysis."""
        # Extract numeric price
        if "price" in self.df.columns:
            self.df["price_num"] = (
                self.df["price"]
                .astype(str)
                .str.replace(r"[\$,]", "", regex=True)
                .astype(float)
            )

        # Extract numeric rating (e.g., "4.7 out of 5 stars" -> 4.7)
        if "rating" in self.df.columns:
            self.df["rating_num"] = (
                self.df["rating"]
                .astype(str)
                .str.extract(r"([\d.]+)")[0]
                .astype(float)
            )

        # Count images
        if "images" in self.df.columns:
            self.df["image_count_num"] = (
                self.df["images"]
                .astype(str)
                .apply(lambda x: len([s for s in x.split() if s.strip() and s.startswith("http")]) if x != "nan" else 0)
            )

    def generate_summary(self) -> Dict[str, Any]:
        """Generate executive summary.

        Returns:
            Dictionary with summary statistics
        """
        summary = {
            "total_products": len(self.df),
            "timestamp": datetime.now().isoformat(),
            "csv_file": str(self.csv_path),
        }

        if "price_num" in self.df.columns:
            valid_prices = self.df["price_num"].dropna()
            if len(valid_prices) > 0:
                summary.update({
                    "price_min": float(valid_prices.min()),
                    "price_max": float(valid_prices.max()),
                    "price_avg": float(valid_prices.mean()),
                    "price_median": float(valid_prices.median()),
                })

        if "rating_num" in self.df.columns:
            valid_ratings = self.df["rating_num"].dropna()
            if len(valid_ratings) > 0:
                summary.update({
                    "rating_min": float(valid_ratings.min()),
                    "rating_max": float(valid_ratings.max()),
                    "rating_avg": float(valid_ratings.mean()),
                    "rating_median": float(valid_ratings.median()),
                })

        if "image_count_num" in self.df.columns:
            summary["total_images"] = int(self.df["image_count_num"].sum())

        return summary

    def analyze_price_distribution(self) -> Dict[str, Any]:
        """Analyze price distribution.

        Returns:
            Price distribution statistics
        """
        if "price_num" not in self.df.columns:
            return {"error": "Price data not available"}

        prices = self.df["price_num"].dropna()
        if len(prices) == 0:
            return {"error": "No valid price data"}

        # Create price ranges
        bins = [0, 10, 20, 30, 50, 100, float("inf")]
        labels = ["$0-10", "$10-20", "$20-30", "$30-50", "$50-100", "$100+"]
        ranges = pd.cut(prices, bins=bins, labels=labels, right=False)

        return {
            "distribution": {str(k): int(v) for k, v in ranges.value_counts().items()},
            "quartiles": {
                "q1": float(prices.quantile(0.25)),
                "q2": float(prices.quantile(0.50)),
                "q3": float(prices.quantile(0.75)),
            },
        }

    def analyze_rating_distribution(self) -> Dict[str, Any]:
        """Analyze rating distribution.

        Returns:
            Rating distribution statistics
        """
        if "rating_num" not in self.df.columns:
            return {"error": "Rating data not available"}

        ratings = self.df["rating_num"].dropna()
        if len(ratings) == 0:
            return {"error": "No valid rating data"}

        # Create rating buckets
        bins = [0, 3, 3.5, 4, 4.5, 5]
        labels = ["<3", "3-3.5", "3.5-4", "4-4.5", "4.5-5"]
        buckets = pd.cut(ratings, bins=bins, labels=labels, right=False)

        return {
            "distribution": {str(k): int(v) for k, v in buckets.value_counts().items()},
            "five_star_count": int((ratings >= 4.5).sum()),
            "low_rating_count": int((ratings < 3.5).sum()),
        }

    def find_opportunities(self, min_rating: float = 4.5, max_price: float = 30.0) -> List[Dict[str, Any]]:
        """Find high-rated low-price products.

        Args:
            min_rating: Minimum rating threshold
            max_price: Maximum price threshold

        Returns:
            List of opportunity products
        """
        if "rating_num" not in self.df.columns or "price_num" not in self.df.columns:
            return []

        mask = (self.df["rating_num"] >= min_rating) & (self.df["price_num"] <= max_price)
        opportunities = self.df[mask].copy()

        results = []
        for _, row in opportunities.iterrows():
            results.append({
                "asin": row.get("asin", "N/A"),
                "title": row.get("title", "N/A")[:80],
                "price": row.get("price", "N/A"),
                "rating": row.get("rating", "N/A"),
                "url": row.get("url", "N/A"),
            })

        return sorted(results, key=lambda x: float(x["rating"].split()[0]) if isinstance(x["rating"], str) and x["rating"][0].isdigit() else 0, reverse=True)

    def get_top_products(self, n: int = 10, by: str = "rating") -> List[Dict[str, Any]]:
        """Get top N products.

        Args:
            n: Number of products to return
            by: Sort by "rating" or "price" (asc/desc)

        Returns:
            List of top products
        """
        if by == "rating" and "rating_num" in self.df.columns:
            sorted_df = self.df.nlargest(n, "rating_num")
        elif by == "price_asc" and "price_num" in self.df.columns:
            sorted_df = self.df.nsmallest(n, "price_num")
        elif by == "price_desc" and "price_num" in self.df.columns:
            sorted_df = self.df.nlargest(n, "price_num")
        else:
            sorted_df = self.df.head(n)

        results = []
        for _, row in sorted_df.iterrows():
            results.append({
                "asin": row.get("asin", "N/A"),
                "title": row.get("title", "N/A")[:80],
                "price": row.get("price", "N/A"),
                "rating": row.get("rating", "N/A"),
                "url": row.get("url", "N/A"),
            })

        return results

    def generate_markdown_report(self) -> str:
        """Generate comprehensive markdown report.

        Returns:
            Markdown formatted report
        """
        summary = self.generate_summary()
        price_dist = self.analyze_price_distribution()
        rating_dist = self.analyze_rating_distribution()
        opportunities = self.find_opportunities()
        top_rated = self.get_top_products(10, by="rating")

        lines = [
            "# Amazon Crawler Data Report",
            "",
            f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Source**: `{self.csv_path.name}`",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| **Total Products** | {summary['total_products']:,} |",
        ]

        if "price_avg" in summary:
            lines.extend([
                f"| **Price Range** | ${summary['price_min']:.2f} - ${summary['price_max']:.2f} |",
                f"| **Average Price** | ${summary['price_avg']:.2f} |",
                f"| **Median Price** | ${summary['price_median']:.2f} |",
            ])

        if "rating_avg" in summary:
            lines.extend([
                f"| **Average Rating** | {summary['rating_avg']:.2f} ⭐ |",
                f"| **Rating Range** | {summary['rating_min']:.1f} - {summary['rating_max']:.1f} ⭐ |",
            ])

        if "total_images" in summary:
            lines.append(f"| **Total Images** | {summary['total_images']:,} |")

        lines.extend(["", "---", "", "## Price Distribution", ""])

        if "distribution" in price_dist:
            lines.append("| Price Range | Count | Percentage |")
            lines.append("|-------------|-------|------------|")
            total = sum(price_dist["distribution"].values())
            for range_label, count in price_dist["distribution"].items():
                pct = (count / total) * 100
                lines.append(f"| {range_label} | {count} | {pct:.1f}% |")

        lines.extend(["", "---", "", "## Rating Distribution", ""])

        if "distribution" in rating_dist:
            lines.append("| Rating Range | Count | Percentage |")
            lines.append("|--------------|-------|------------|")
            total = sum(rating_dist["distribution"].values())
            for range_label, count in rating_dist["distribution"].items():
                pct = (count / total) * 100
                lines.append(f"| {range_label} | {count} | {pct:.1f}% |")

        lines.extend(["", "---", "", "## Top Opportunities", "",
                     "High-rated products with competitive prices:"])

        if opportunities:
            lines.extend(["| ASIN | Title | Price | Rating | Link |",
                         "|-----|-------|-------|--------|------|"])
            for opp in opportunities[:10]:
                lines.append(f"| {opp['asin']} | {opp['title']} | {opp['price']} | {opp['rating']} | [View]({opp['url']}) |")
        else:
            lines.append("*No opportunities found with current criteria*")

        lines.extend(["", "---", "", "## Top Rated Products", ""])

        if top_rated:
            lines.extend(["| Rank | ASIN | Title | Price | Rating | Link |",
                         "|------|----- |-------|-------|--------|------|"])
            for i, product in enumerate(top_rated, 1):
                lines.append(f"| {i} | {product['asin']} | {product['title']} | {product['price']} | {product['rating']} | [View]({product['url']}) |")

        lines.extend(["", "---", "", "## Data Quality", ""])

        # Check for missing values
        for col in self.df.columns:
            missing = self.df[col].isna().sum()
            if missing > 0:
                lines.append(f"- **{col}**: {missing} missing values ({missing/len(self.df)*100:.1f}%)")

        if all(self.df[col].isna().sum() == 0 for col in self.df.columns):
            lines.append("*✓ All data fields complete*")

        lines.extend(["", "---", "", f"*Report generated by Amazon Crawler Report Generator*"])

        return "\n".join(lines)

    def save_report(self, output_path: str = None):
        """Save report to file.

        Args:
            output_path: Output file path (default: CSV_name_report.md)
        """
        if output_path is None:
            output_path = self.csv_path.stem + "_report.md"

        output_path = Path(output_path)

        # Save markdown report
        markdown = self.generate_markdown_report()
        output_path.write_text(markdown, encoding="utf-8")

        # Save JSON statistics
        json_path = output_path.with_suffix(".json")
        stats = {
            "summary": self.generate_summary(),
            "price_distribution": self.analyze_price_distribution(),
            "rating_distribution": self.analyze_rating_distribution(),
            "opportunities": self.find_opportunities(),
            "top_products": self.get_top_products(10, by="rating"),
        }
        json_path.write_text(json.dumps(stats, indent=2, ensure_ascii=False), encoding="utf-8")

        print(f"✓ Markdown report saved: {output_path}")
        print(f"✓ JSON statistics saved: {json_path}")

        # Print console summary
        self._print_console_summary()

    def _print_console_summary(self):
        """Print summary to console."""
        summary = self.generate_summary()
        opportunities = self.find_opportunities()

        print("\n" + "=" * 60)
        print("AMAZON CRAWLER REPORT SUMMARY")
        print("=" * 60)
        print(f"Total Products:  {summary['total_products']:,}")

        if "price_avg" in summary:
            print(f"Price Range:     ${summary['price_min']:.2f} - ${summary['price_max']:.2f}")
            print(f"Average Price:   ${summary['price_avg']:.2f}")

        if "rating_avg" in summary:
            print(f"Average Rating:  {summary['rating_avg']:.2f} ⭐")

        if opportunities:
            print(f"\nTop Opportunities ({len(opportunities)} found):")
            for opp in opportunities[:5]:
                print(f"  - {opp['title'][:60]}... | {opp['price']} | {opp['rating']}")

        print("=" * 60 + "\n")


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Generate reports from Amazon crawler CSV output",
        epilog="Example: python crawler_report.py amazon_products.csv",
    )
    parser.add_argument(
        "csv_file",
        type=str,
        help="Path to the CSV file generated by crawler",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        help="Output report filename (default: CSV_name_report.md)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output JSON statistics to stdout",
    )

    args = parser.parse_args()

    try:
        report = CrawlerReport(args.csv_file)

        if args.json:
            stats = {
                "summary": report.generate_summary(),
                "price_distribution": report.analyze_price_distribution(),
                "rating_distribution": report.analyze_rating_distribution(),
                "opportunities": report.find_opportunities(),
            }
            print(json.dumps(stats, indent=2, ensure_ascii=False))
        else:
            report.save_report(args.output)

    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error generating report: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
